In [2]:
import numpy as np
import pandas as pd

In [21]:

class SGD:
    def __init__(self, fit_intercept=True, copy_X=True,
                 alpha=0.0001, epochs=100000, weight_decay=0.9,batch_size=1,shuffle=True):
        self.fit_intercept = fit_intercept
        self.copy_X = copy_X
        self._alpha = alpha
        self._epochs = epochs
        self._BATCH_SIZE = batch_size
        self._cost_history = []

        self._coef = None
        self._intercept = None
        self._new_X = None
        self._w_history = None
        self._weight_decay = weight_decay

    def cost(self, h, y):
        m = y.size
        predictions = h
        sqErrors = (predictions - y)

        J = (1.0/(2*m)) * sqErrors.T.dot(sqErrors)
        return J

    def hypothesis_function(self, X, theta):
        return X.dot(theta)

    def gradient(self, X, theta):
        predictions = X.dot(theta)
        m = X.shape[0]
        for i in range(theta.size):
            partial_marginal = X[:,i]
            errors_xi = (predictions - y) * partial_marginal
            theta[i] = theta[i] - self._alpha * (1.0/m) * errors_xi.sum()
        return theta
    
    def fit(self,X,y):
        if self.fit_intercept == True:
            make_ones = k = np.ones([X.shape[0],1])
            np.hstack((make_ones,X))
        
        cost_history = []
        theta_history = []

        theta = np.random.normal((X.shape[0],1))
        
        for _ in range(self._epochs):
            self.X_copy = np.copy(X)
            
            if self.is_SGD:
                shuffle_index = np.random.shuffle(self.X_copy.shape[0])
            batch = len(self.X_copy) // self._BATCH_SIZE
            
            for batch_count in range(batch):
                X_batch = np.copy(X_copy[batch_count*self.BATCH_SIZE : (batch_count+1)*BATCH_SIZE])
                theta = self.gradient(X_batch,theta)#theta값 수정 필요...
            print("Number of epoch : %d" %epoch)
            if _ % 1000 == 0:
                theta_history.append(theta)
                cost_history.append(self.cost(self.hypothesis_function(X,theta),y))
        self._coef = theta
        return theta,np.array(cost_history),np.array(theta_history)

        
        
    def predict(self, X):
        return X.dot(self.coef)
        

    @property
    def coef(self):
        return self._coef

    @property
    def intercept(self):
        return self._intercept

    @property
    def weights_history(self):
        return np.array(self._w_history)

    @property
    def cost_history(self):
        return self._cost_history


In [22]:
from sklearn.datasets.samples_generator import make_regression

In [23]:
X,y = make_regression(n_samples=1000,n_features=1,noise=10,random_state=42)

In [24]:
sgd_lr = SGD(alpha=0.001,epochs=10000,batch_size=10,shuffle=True)

In [3]:
X = np.array([[1,2],[2,4],[5,8]])

In [11]:
theta = np.random.normal((X.shape[0],1))

In [16]:
X

array([[1, 2],
       [2, 4],
       [5, 8]])

In [15]:
X.dot(theta)

array([ 2.3294799 ,  4.65895981, 11.4630002 ])

In [17]:
theta

array([2.14508058, 0.09219966])

In [18]:
X[:,0]

array([1, 2, 5])

In [20]:
y = np.array([4,8,12])

In [35]:
hypp = X.dot(theta) - y

In [36]:
(X.dot(theta) - y)

array([-1.6705201 , -3.34104019, -0.5369998 ])

In [67]:
(X.dot(theta) - y)

array([-1.6705201 , -3.34104019, -0.5369998 ])

In [69]:
X = np.array([[1,2],[1,2],[1,2]])
X

array([[1, 2],
       [1, 2],
       [1, 2]])

In [73]:
0.01*hypp.dot(X)

array([-0.0554856, -0.1109712])

In [74]:
theta

array([2.14508058, 0.09219966])

In [78]:
theta - 0.001*hypp.dot(X)*(1.0/X.shape[0])

array([2.1469301, 0.0958987])

In [99]:
class SGD:
    def __init__(self, fit_intercept=True, copy_X=True,
                 alpha=0.0001, epochs=1000000, weight_decay=0.9):
        self.fit_intercept = fit_intercept
        self.copy_X = copy_X
        self._alpha = alpha
        self._epochs = epochs

        self._cost_history = []

        self._coef = None
        self._intercept = None
        self._new_X = None
        self._w_history = None
        self._weight_decay = weight_decay

    def cost(self, h, y):
        m = y.size
        predictions = h
        sqErrors = (predictions - y)

        J = (1.0/(2*m)) * sqErrors.T.dot(sqErrors)
        return J

    def hypothesis_function(self, X, theta):
        return X.dot(theta)

    def gradient(self, X, theta):
        predictions = X.dot(theta)
        m = X.shape[0]
        
        hypo = (predictions-y).dot(X)
        theta = theta - self._alpha * (1.0/m) * hypo
        
        #for i in range(theta.size):
        #    partial_marginal = X[:,i]
        #    errors_xi = (predictions - y) * partial_marginal
        #    theta[i] = theta[i] - self._alpha * (1.0/m) * errors_xi.sum()
        
        return theta
    
    def fit(self,X,y):
        if self.fit_intercept == True:
            make_ones = k = np.ones([X.shape[0],1])
            np.hstack((make_ones,X))
        
        cost_history = []
        theta_history = []

        theta = np.random.normal((X.shape[0],1))
        
        for _ in range(self._epochs):
            theta = self.gradient(X,theta)
            
            if _ % 1000 == 0:
                theta_history.append(theta)
                cost_history.append(self.cost(self.hypothesis_function(X,theta),y))
        
        self._coef = theta
        return theta,np.array(cost_history),np.array(theta_history)

        
        
    def predict(self, X):
        return X.dot(self.coef)

    @property
    def coef(self):
        return self._coef

    @property
    def intercept(self):
        return self._intercept

    @property
    def weights_history(self):
        return np.array(self._w_history)

    @property
    def cost_history(self):
        return self._cost_history


In [83]:

if __name__ == "__main__":
    X = np.array([[1,2],[1,4],[1,5]])
    y = np.array([4,8,12])
    my_sgd = SGD(fit_intercept=True)
    my_sgd.fit(X,y)

In [100]:
X = np.array([[1,2],[1,4],[1,5]])
y = np.array([4,8,12])
my_sgd = SGD(fit_intercept=True)
my_sgd.fit(X,y)

(array([-1.42833202,  2.57136967]),
 array([7.82420537, 1.38306122, 1.09902266, 1.07060154, 1.0531014 ,
        1.03637028, 1.01998115, 1.00391028, 0.98815079, 0.97269663,
        0.95754188, 0.94268074, 0.92810752, 0.91381664, 0.89980263,
        0.88606013, 0.87258388, 0.85936871, 0.84640958, 0.83370152,
        0.82123966, 0.80901924, 0.79703558, 0.78528409, 0.77376027,
        0.76245972, 0.7513781 , 0.74051118, 0.72985479, 0.71940486,
        0.70915739, 0.69910846, 0.68925421, 0.67959087, 0.67011476,
        0.66082224, 0.65170974, 0.6427738 , 0.63401098, 0.62541793,
        0.61699136, 0.60872805, 0.60062483, 0.59267861, 0.58488633,
        0.57724502, 0.56975176, 0.56240367, 0.55519794, 0.54813182,
        0.54120259, 0.53440761, 0.52774428, 0.52121004, 0.5148024 ,
        0.5085189 , 0.50235714, 0.49631475, 0.49038943, 0.48457891,
        0.47888096, 0.4732934 , 0.46781409, 0.46244095, 0.4571719 ,
        0.45200493, 0.44693807, 0.44196937, 0.43709694, 0.43231891,
        0.42

In [87]:
from sklearn import linear_model 

In [88]:
regr = linear_model.LinearRegression()

In [90]:
regr.fit(X,y)

LinearRegression()

In [96]:
testX = np.array([[6,2],[2,4],[4,5]])

In [97]:
regr.predict(testX)

array([ 3.71428571,  8.85714286, 11.42857143])

In [101]:
my_sgd.predict(testX)

array([-3.42725279,  7.42881462,  7.14352025])